name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install BATS
        run: sudo apt-get update && sudo apt-get install -y bats
      - name: run tests
        run: bats test/test_script.bats
      - name: Build Docker image
        run: docker build -t usuario/mi-imagen-nginx .
