name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install BATS
        run: sudo apt-get update && sudo apt-get install -y bats

      - name: Run tests
        run: bats test/test_script.bats

      - name: Make metrics_summary.sh executable
        run: chmod +x test/metrics_summary.sh

      - name: Show test metrics summary
        run: bash test/metrics_summary.sh

      - name: Build Docker image
        run: docker build -t usuario/mi-imagen-nginx .

      - name: Run container
        run: |
          docker run --name contenedor-prueba -d usuario/mi-imagen-nginx "Diego"
          sleep 2

      - name: Show container logs
        run: docker logs contenedor-prueba

      - name: Cleanup
        if: always()
        run: |
          docker rm -f contenedor-prueba || true
          docker rmi usuario/mi-imagen-nginx || true
